### ISSUE TITLE
Icon Map

### ISSUE THREAD

**Issue by ajmueller** [isitedesign/Phoenix#118]
Similar to @elseloop's work on turning our `$colors` variable to a map, we should do the same with our icons for Icomoon.

**Comment by ajmueller** [comment]
From http://ericsuzanne.com/pres/map-magic/:

```scss
[data-icon]:before {
	@extend %icon;
	content: attr(data-icon);
}

@each $name, $glyph in $icons {
	[data-icon='#{$icon}']:before {
		content: map-get($icons, $name);
	}
}
````
