### ISSUE TITLE
Functions/Mixins have conflicting global and local variable names.

### ISSUE THREAD

**Issue by obrogaming** [isitedesign/Phoenix#79]
For our project we opted to use our existing scss compiler [http://leafo.net/scssphp/](http://leafo.net/scssphp/)  vs node. Everything ports over perfectly, except one little tweak that I think might be worth mentioning for others. 

Also I'm hesitant to call this an issue, but if source is updated with the fix below, this will ensure that Phoenix could work on a number of other compiler platforms and pick up some more users without effecting the node compile process at all.

# ::The Problem::
Under /Assets/src/css/functions/* we have a lot of awaiting parameter variables for each function. For instance:
```css
@function divideColumns($columns) {
	@return 100% / $columns;
}
```

The problem here is that these variables are not being treated as local vars by our compiler (compass as well), but are falling back to global vars if one is found. 

So for the above example, no matter what number is sent to the function, the function reads $columns from /Assets/src/css/variables/_grid.scss. This issue is most noticable when trying to utilize the @include column(X,X); mixin in /Assets/src/css/mixins/grid/_semantic-grid.scss

```css
@mixin column($columns, $padding: $gutterInPx, $nested: false, $alignment: false) {
	@if $alignment == centered {
		@extend %column-config;
		padding: $padding;

		&:first-child {
			margin-top: 0;
		}

		@include respond(breakpointMedium) {
			clear: both;
			margin-left: centered($columns);
			margin-top: 0;
			width: columns($columns);
		}
	}
	@else {
		@extend %column-config;
		padding: $padding;

		@if $nested == nested {
			margin-top: $gutterInPx;

			&:first-child {
				margin-top: 0;
			}
		}

		@include respond(breakpointMedium) {
			margin-top: 0;
			width: columns($columns);
		}
	}
}
```

this mixin uses the columns(X) function in /Assets/src/css/functions/_grid-calc.scss:
```css
@function columns($num){
	@return (oneCol() * $num);
}
```
This function uses another function called oneCol() found in the same file:
```css
@function oneCol() {
	@return (100% / $columns);
}
```
And ultimately this oneCol() function uses the global $columns var that conflicts with the @mixin column's use of local $columns.

# ::The Solution::
Prefix all local function vars with $_* underscores to preserve them as indeed local to the function, like so :
```css
@function divideColumns($_columns) {
	@return 100% / $_columns;
}
```

# ::WARNING::
Please be careful if when doing this to not kill fall-back global vars that are needed still in functions such as:
```css
@function image($imageName, $directory: $imagesFolder) {
	$imageName: unquote($imageName);
	$directory: unquote($directory);

	@return url('#{$directory}#{$imageName}');
}
```
becomes:

```css
@function image($_imageName, $_directory: $imagesFolder) {
      $_imageName: unquote($_imageName);
      $_directory: unquote($_directory);

      @return url('#{$_directory}#{$_imageName}');
}
```

Notice how we leave $imagesFolder alone? This is cause $_directory can be set, or fall-back to the global $imagesFolder, so we need not set the fall-backs to be prefixed.
