### ISSUE TITLE
Accessibility Class on Android 4.1

### ISSUE THREAD

**Issue by ajmueller** [isitedesign/Phoenix#80]
On a recent project, I had an issue with the accessibility class on Android 4.1 where its application to an anchor resulted in the anchor's text being displayed in the viewport:

![image](https://cloud.githubusercontent.com/assets/1442179/4943805/02c70006-65f8-11e4-9588-2844bd5340c5.png)

The fix that I found in this case was to change the accessibility class to have the following styling:

```css
.accessibility {
	height: 0;
	left: -999em;
	line-height: 0;
	position: absolute;
}
```
