### ISSUE TITLE
Aspect Ratio with Pseudo Element

### ISSUE THREAD

**Issue by ajmueller** [isitedesign/Phoenix#87]
On a client project recently we needed to limit the width of videos.  To maintain aspect ratio, but also restrict width, the aspect ratio mixin had to be altered.  This is what we used:

```scss
@mixin aspect-ratio($width: 16, $height: 9) {
	position: relative;	// context for direct descendant

	// container to maintain aspect ratio
	&:before {
		content: '';
		display: block;
		padding-top: percentage(parseInt($height) / parseInt($width));
	}
```

This will require some more testing, but it should be a good enhancement to the functionality.
