### ISSUE TITLE
Use generated content bullets on uls

### ISSUE THREAD

**Issue by stoff** [isitedesign/Phoenix#93]
**Rationale**

By using generated content we can insert a unicode bullet and normalize the appearance of bullets across all platforms.

**Documentation needs**

It would be good to document drawbacks - bullets on nested uls will appear the same - no switching to disc, etc.  If this is desired, this style needs to be overridden for nested uls. For most applications, however, indentation seems to provide enough of a visual cue to convey the sense of 'nested-ness'.

**Implementation notes**
* assumes vertical rhythm is addressed elsewhere.
* float is on the :before to prevent a whitespace issue: whitespace at the beginning of the li will be rendered by most clients (correctly) because we're adding/generating content before it.

**Snippet**
```scss
$bulletWidth: em(18);
ul {
	list-style-image: none;
	list-style: none;
	margin-left: $bulletWidth;

	li:before {
		content: "\2022";
		display: inline-block;
		float: left;
		margin-left: -$bulletWidth;
		text-align: center;
		width: $bulletWidth;
	}
}
```
